### ISSUE TITLE
Plugin cannot see Virtual Machines made with the Azure Resource Manager Templates.

### ISSUE THREAD

**Issue by erichexter** [JetBrains/teamcity-azure-plugin#11]
I made an ARM template for our Team City Build Agents. the plugin cannot see those virtual machines in the Profile Configuration page.  This is identical to with the fact that the old Azure portal cannot see t that VM as well, it is only visible with the Resource Management APIs.

**Comment by erichexter** [comment]
It appears that you would need to use the additional resource manager apis to find virtual machines created as well as manage them. 

https://github.com/Azure/azure-sdk-for-java/tree/master/resource-management

**Comment by paksv** [comment]
Opened ticket in our tracker: https://youtrack.jetbrains.com/issue/TW-42562

**Comment by erichexter** [comment]
Thanks, I started a chain with Microsoft on an Azure Insiders list.  I think the fact that there are two sets of APIs is unacceptable from a vendors point of view.  I am going to rework, our agent creation script to use the original service management apis, instead of the resource manager apis.  Feel free to close this issue, since you have it tracked else where.

**Comment by okesare** [comment]
Any update on ARM support in the plugin?

**Comment by ArturDorochowicz** [comment]
I too hope to see this released soon.

An interesting aspect of the Azure plugin is that it does two things. One is to start and stop existing VMs and the other is to create and destroy VMs from images (I haven't used this one).

In the ARM world the first is probably pretty much the same, just start and stop a VM. The other - well,  one could imagine that TeamCity would be able to deploy VMs (and more) from ARM templates. That would be very interesting.

**Comment by dtretyakov** [comment]
Azure Resource Manager plugin for TeamCity is available for [download](https://github.com/JetBrains/teamcity-azure-plugin#installation).
