### ISSUE TITLE
Agent manually started in Azure should not modify agent properties

### ISSUE THREAD

**Issue by konste** [JetBrains/teamcity-azure-plugin#17]
When Agent is run on Azure VM it always sets azure.instance.name and ultimately presents it to server as Agent name, even when Server is not configured to use Cloud Agents and the agent is manually configured to use different name through **buildAgent.properties**, like this:

name=AZSC-TCBUILD-1
system.agent.name=AZSC-TCBUILD-1
teamcity.agent.name=AZSC-TCBUILD-1

All of the above is ignored and azure instance name is used instead. This creates substantial problem, because all VMs created (manually) from the same image get that instance name identical and they collide when try to register on TeamCity server.

**Comment by Aaronontheweb** [comment]
Any update on this? Dealing with this issue too.

**Comment by paksv** [comment]
removing azure cloud plugin will help, if you are not using Cloud agents. If you do - please wait for a fix this week.

**Comment by paksv** [comment]
fixed in 0.2.63.
