### ISSUE TITLE
Allow cloud agents to be assigned to a particular Azure virtual network

### ISSUE THREAD

**Issue by dlwyatt** [JetBrains/teamcity-azure-plugin#18]
Right now, they are created in such a way that communication with the TeamCity server takes place over the public internet.  Because agents don't support HTTPS (and JetBrains has stated that the solution for this is to place the agents / server on private networks, or to enable VPN), this makes the Azure plug-in pretty useless in its current state, if encrypted agent traffic is desired.

**Comment by dlwyatt** [comment]
Looks like this was addressed in some recent commits, judging from the messages.  I'll check out the code, and close this issue if it's all set now.

**Comment by paksv** [comment]
Yeah, https://github.com/JetBrains/teamcity-azure-plugin/pull/14 was addressing the issue
