### ISSUE TITLE
Mismatch between the agent name and the virtual machine name

### ISSUE THREAD

**Issue by sdurandeu** [JetBrains/teamcity-azure-plugin#20]
I'm using the 0.2.67 version of the plugin, with the fresh clone behavior (using an VM image). For creating the image, I've removed the build agent `name` from the  `buildAgent.properties` file.  However, when the plugin creates the image it sets the name to the 'ip_XX.112.138.140-1' value, and does not use the prefix defined in the plugin settings (e.g `MYBLD-##`). The problem is that I cannot map between the name of the agents in TeamCity and the name of the VMs in the Azure management portal.

I'n not sure if this is an issue, but I believe that on a previous version, the plugin was setting the name using the prefix configured in the Plugin properties. Any ideas? I believe this might be a side effect of the fix in #17.

**Comment by paksv** [comment]
It looks like agent part of plugin is not able to determine whether it was launched by TC or not. Are you using generalized (sysprep-prepared) image?

**Comment by sdurandeu** [comment]
I don't run sysprep myself. I just capture the image and do not check the "I have run Sysprep on the virtual machine" box when creating the image.

**Comment by paksv** [comment]
Please try to check this checkbox (and also prepare the image with sysprep). Actually, without doing this, plugin is unable to reliably determine whether the instance was launched by TC in Azure or not.

**Comment by bblanchon** [comment]
I'm having the same issue with sysprep'd VMs.
All my agents are named "localhost-XXX", completely ignoring the prefix.
This used to work fine with version 0.2.58.

**Comment by paksv** [comment]
@bblanchon please attach teamcity-agent.log from such VM

**Comment by Aaronontheweb** [comment]
@paksv I only have this issue when I **have** sysprepped the VMs. Everything works fine otherwise.

**Comment by dtretyakov** [comment]
This issue was fixed in the plugin versions 0.4+
