### ISSUE TITLE
Any plans to support the new Azure Resource Manager mode?

### ISSUE THREAD

**Issue by jinhong-** [JetBrains/teamcity-azure-plugin#21]
Azure is now moving to the ARM instead of the classic mode. Is there any plans to move to ARM or create a version that support ARM?

**Comment by dtretyakov** [comment]
It is a duplicate for issue #11, we have an issue [TW-42562](https://youtrack.jetbrains.com/issue/TW-42562) in the tracker.
ARM will be available in the further plugin versions.
