### ISSUE TITLE
Windows Agents launched simultaneously have conflicting ports.

### ISSUE THREAD

**Issue by jamestalmage** [JetBrains/teamcity-azure-plugin#23]
I am noticing an issue when launching multiple cloud agents, here is what I experience:

1. A build trigger happens, and 4 builds are added to the Queue
2. I have my instance limit set to `2`, so two instances are launched.
3. Both instances boot with `endpoint` ports set to `9090` (I can see this on the Azure portal, and in the agent information screen).
4. One eventually experiences a "communication error", and is shut down.
5. A third instance is launched in place of the instance that was shut down, and given endpoint port `9091`.
6. Things seem to work normally after that.

My only explanation is that it is somehow failing to recognize the eventual conflict of ports.

**Comment by dtretyakov** [comment]
@jamestalmage, thanks for reporting this issue.
You can download latest plugin build where it was fixed:
https://github.com/JetBrains/teamcity-azure-plugin#installation
