### ISSUE TITLE
Account for startup time when deciding to start another agent.

### ISSUE THREAD

**Issue by gambrose** [JetBrains/teamcity-azure-plugin#24]
Starting a machine on Azure can be slow, about 5 mins.
If an agent is already running then it is quite possible that it will finish its current build and start building the queued build before the new agent has come online. Which means that the new agent comes online it has nothing to do and was started unnecessarily.

**Comment by dtretyakov** [comment]
@gambrose, thank you for reporting. 

It is a common case for all cloud integrations which is reported in the TeamCity tracker: https://youtrack.jetbrains.com/issue/TW-41545

You can vote for it and monitor changes.
