### ISSUE TITLE
Sometimes cloud launched agents show as Unauthorized

### ISSUE THREAD

**Issue by jamestalmage** [JetBrains/teamcity-azure-plugin#25]
It's intermittent, but the plugin seems to sometimes fail to authorize a client after launch. 

<img width="1184" alt="screenshot 2016-06-19 15 47 29" src="https://cloud.githubusercontent.com/assets/4082216/16179486/52825bf4-3635-11e6-85e2-86c786c57aaa.png">

Is there a log I can look at and maybe see why this is happening? Is this a known issue?

I'm using classic mode. Would switching to Resource Manager improve anything?

It's pretty frustrating to watch an instance I'm paying for sit there idle.

**Comment by dtretyakov** [comment]
@jamestalmage, could you please provide `teamcity-clouds.log` file to investingate such failures. Consider to create issue in the [youtrack](https://youtrack.jetbrains.com/issues/TW) to provide secure attachments.

Currently Resource Manager is a preferred way to deploy resources, so you can try to use it by following guidelines in the [blog post](https://blog.jetbrains.com/teamcity/2016/04/teamcity-azure-resource-manager/).

**Comment by dtretyakov** [comment]
@jamestalmage, could you also share what is the TeamCity build agent startup type and type of account (user / SYSTEM) in your vm images?

**Comment by dtretyakov** [comment]
This issue was fixed in the plugin versions 0.4+
