### ISSUE TITLE
TC Unable to Retrieve Azure Subscriptions

### ISSUE THREAD

**Issue by westongm** [JetBrains/teamcity-azure-plugin#26]
We installed the ARM plugin to a TC instance on a private server behind a corporate firewall and are unable to retrieve the Azure Subscription with our Client/Tenant ID.  We were successful with using the plugin on a TC instance running in Azure using the same Client/Tenant ID and secret key.  The error has been logged in the winservice.log as follows (console time stamps removed):

[Info] [2016-07-07 11:29:28,913]  ERROR - jdeferred.impl.AbstractPromise - an uncaught exception occured in a AlwaysCallback
[Info] java.lang.IllegalStateException: The request associated with the AsyncContext has already completed processing.
[Info] 	at org.apache.catalina.core.AsyncContextImpl.check(AsyncContextImpl.java:553)
[Info] 	at org.apache.catalina.core.AsyncContextImpl.getResponse(AsyncContextImpl.java:265)
[Info] 	at jetbrains.buildServer.clouds.azure.arm.web.SettingsController$2.onAlways(SettingsController.java:153)
[Info] 	at jetbrains.buildServer.clouds.azure.arm.web.SettingsController$2.onAlways(SettingsController.java:142)
[Info] 	at org.jdeferred.impl.AbstractPromise.triggerAlways(AbstractPromise.java:155)
[Info] 	at org.jdeferred.impl.AbstractPromise.triggerAlways(AbstractPromise.java:142)
[Info] 	at org.jdeferred.impl.DeferredObject.reject(DeferredObject.java:100)
[Info] 	at org.jdeferred.multiple.MasterDeferredObject$3.onFail(MasterDeferredObject.java:76)
[Info] 	at org.jdeferred.impl.AbstractPromise.triggerFail(AbstractPromise.java:122)
[Info] 	at org.jdeferred.impl.AbstractPromise.triggerFail(AbstractPromise.java:113)
[Info] 	at org.jdeferred.impl.DeferredObject.reject(DeferredObject.java:98)
[Info] 	at org.jdeferred.impl.PipedPromise$2.onFail(PipedPromise.java:42)
[Info] 	at org.jdeferred.impl.AbstractPromise.triggerFail(AbstractPromise.java:122)
[Info] 	at org.jdeferred.impl.AbstractPromise.triggerFail(AbstractPromise.java:113)
[Info] 	at org.jdeferred.impl.DeferredObject.reject(DeferredObject.java:98)
[Info] 	at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$29.failure(AzureApiConnectorImpl.java:926)
[Info] 	at com.microsoft.rest.ServiceResponseCallback.onFailure(ServiceResponseCallback.java:37)
[Info] 	at retrofit2.OkHttpCall$1.onFailure(OkHttpCall.java:119)
[Info] 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:140)
[Info] 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
[Info] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[Info] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[Info] 	at java.lang.Thread.run(Unknown Source)

We've performed the "Configure TeamCity to Use Proxy Server for Outgoing Connections" stated in the TC Documentation.  Anyone have any thoughts on what we are missing?

**Comment by dtretyakov** [comment]
@westongm, thanks for reporting this issue.
You can download [latest version](https://github.com/JetBrains/teamcity-azure-plugin#installation) of Resource Manager plugin where it was fixed.

**Comment by westongm** [comment]
@dtretyakov 

Thanks. We were able to get through the proxy.  Do you know of a way to hide the credentials so they do not appear on the "Diagnostics" screen of the UI?

**Comment by dtretyakov** [comment]
@westongm,

You can use roles and permissions to restrict access to the administrator pages. Regular users could not access it.
