### ISSUE TITLE
Support FreeBSD agent

### ISSUE THREAD

**Issue by bblanchon** [JetBrains/teamcity-azure-plugin#3]
I'm trying to run a FreeBSD agent, based on [this image from VM Depot](https://vmdepot.msopentech.com/Vhd/Show?vhdId=49971&version=51112).

Unfortunately, I encounter the following error:

    ds.azure.AzurePropertiesReader - Azure integration is disablled: unsupported OS family amd64(10.1-release)

See [AzurePropertiesReader.java, line 74](https://github.com/JetBrains/teamcity-azure-plugin/blob/d8bc8cfa1e7a5cb1607d008ddd884716c03e98cc/teamcity-azure-plugin-agent/src/main/java/jetbrains/buildServer/clouds/azure/AzurePropertiesReader.java#L74)

**Comment by paksv** [comment]
Link to actual issue: https://youtrack.jetbrains.com/issue/TW-40248
