### ISSUE TITLE
Reuse Cloud Agent Suffixes

### ISSUE THREAD

**Issue by westongm** [JetBrains/teamcity-azure-plugin#35]
We need the plugin to reuse cloud agent suffix numbers to avoid issues with Active Directory domain constraints.  Currently, all of our cloud agents are joined to our AD domain but are not removed when the agents are deleted.  There is an upper bound on the number of agents our accounts can concurrently have added to the domain.  This resulted in our cloud agents failing to join our network when being provisioned.  If the plugin reused suffixes, they could rejoin with a name already on the domain and alleviate the additional steps of removing potentially hundreds of machine names from the Active Directory domain.

**Comment by dtretyakov** [comment]
@westongm, recent change in issue https://github.com/JetBrains/teamcity-azure-plugin/issues/34 brings ability to reuse created virtual machines and it should help in your case.

Please try to [download updated plugin](https://plugins.jetbrains.com/plugin/9260?pr=teamcity) from the gallery and enable `Reuse allocated virtual machines` for your images.

**Comment by dtretyakov** [comment]
@westongm, it was fixed in the [ARM plugin](https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support) version 0.5.1.
