### ISSUE TITLE
Deploy agents to specific Azure Resource Manager Resource Group

### ISSUE THREAD

**Issue by Aaronontheweb** [JetBrains/teamcity-azure-plugin#36]
It'd be really helpful if we could just deploy to a specific Resource Group so we don't have to provide the TeamCity AD application with contributor access to the entire subscription. Is that on the roadmap for a future release?

**Comment by jacksobt** [comment]
This would also be immensely helpful for the cloud CI system that we are setting up as well. Having to navigate it as it stands currently with our IT department is incredibly difficult.

**Comment by dtretyakov** [comment]
The actual problem when we'll try to implement this feature is a cleanup and concurrent VMs start. ARM deployer does not provide a reliable way to delete deployed resources in the group. Separate resource group per VM does not have such problems since when we're removing it will be destroyed all deployed resources within it.

So while implementing it we need to solve these drawbacks of ARM deployer.

**Comment by konste** [comment]
We desperately wait for this feature to be implemented. Ability to keep all TC cloud agents within particular Resource Group would make it much more manageable. 

I don't quite understand "reliable way to delete deployed resources in the group". What is it exactly you are missing? Currently each agent group contains VM and network interface. All those VMs and matching network interfaces may be placed in the same RG. To delete those reliably you can use [this](http://www.codeisahighway.com/effective-ways-to-delete-resources-in-a-resource-group-on-azure/) - not the script, of course, but the algorithm. Each agent VM is a combination of only two or three resources with very simple dependencies between them. Should be easy to delete an agent by name, deleting its two or three resources in the right order. 
Please share your concerns - we really want to unstuck this feature!

**Comment by dtretyakov** [comment]
[Latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1) supports deploying to specific resource group. Please let me know if it fits your needs.

**Comment by btdevopsteam** [comment]
The latest plugin build works like a charm

Thanks!

**Comment by jacksobt** [comment]
Working great for us as well. Thank you!
