### ISSUE TITLE
Allow to use custom ARM template to start machines

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-azure-plugin#45]
Currently ARM plugin generates ARM templates internally and provides a limited set of customizations.
We can provide advanced mode for customers who needs to use their own custom ARM JSON templates.

**Comment by trzombie** [comment]
I'm very interested in this. Any news?

**Comment by dtretyakov** [comment]
@trzombie, we're still evaluating this feature request. Could you please specify what kind of resources you need to deploy via ARM template?

**Comment by trzombie** [comment]
Examples could be size of disk, additional data disk(s), forced shutdown time etc. In general I would like to have the possibility of using a full custom template, also because this can be stored in source control, versioned etc.

Thanks

**Comment by jacksobt** [comment]
In addition to trzombie's examples above my team would also use this for post-generation configuration tasks (such as joining the domain and updating time zones). Actually, with the use of the ARM template, we would likely use that to deploy the entire VM from a custom image and perform all post-generation configuration tasks.

**Comment by dtretyakov** [comment]
In the [latest plugin builds](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1) you could specify custom ARM template to start virtual machines. Please let me know if you need any additional features related to that mode.

**Comment by dtretyakov** [comment]
It also allows to specify custom script extension for [Linux](https://docs.microsoft.com/en-us/azure/virtual-machines/linux/extensions-customscript) and [Windows](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/extensions-customscript) machines to execute preparation on machine start.

**Comment by tom-dudley** [comment]
@dtretyakov Great to see templates are now supported. Can you clarify whether you support deploying to a single resource group when using a template?

For example, if I have an ARM template with a VM resource with the name 'agent' and a NIC resource with name 'agent-nic' and I tell the plugin to spin up two agents in the same resource group, how are you avoiding clashes of resource names?

**Comment by dtretyakov** [comment]
@tom-dudley, you could use `[parameters('vmName')]` parameter in your template to make and set ids for resources. It'll be filled by generated name on build agent start.

**Comment by tom-dudley** [comment]
@dtretyakov Thanks, I'll give that a go. I assume the generated VM name is based off the 'Name prefix' field. The description of `Unique name prefix to create resource groups` is what threw me off slightly. It sounds as though its more `Unique name prefix of resources`
