### ISSUE TITLE
Set idle timeout per Cloud Image

### ISSUE THREAD

**Issue by aaron-0** [JetBrains/teamcity-azure-plugin#46]
I am using the classic version of the plugin to sleep and wake my agents.

It would be useful if there was a feature to be able to tell an agent not to sleep for say 4h.

I often find myself disabling the agent cloud plugin so I can do maintenance on an Agent without it being shut down.

**Comment by dtretyakov** [comment]
@aaron-0, increasing `Terminate instance idle time` does not help in your case?

![image](https://cloud.githubusercontent.com/assets/1025927/20357962/11404b3e-ac3b-11e6-8ec9-b144730ea7d3.png)

**Comment by aaron-0** [comment]
You are right I'm probably better using that value so at least if I forget to change it back all the agents don't keep running till I realise. I guess I was more after something that could be applied to a single agent

**Comment by dtretyakov** [comment]
Will be fixed as part of #73
