### ISSUE TITLE
Add support for managed disks / snapshots

### ISSUE THREAD

**Issue by SaphuA** [JetBrains/teamcity-azure-plugin#50]
With the new managed disks feature Azure no longer stores vhd files into blob storage. It would be great if the TeamCity Azure Plugin supported this.

The way I see this workflow:
1. Create a new VM with a manged disk
2. Install the VM and run sysprep
3. Create a snapshot of the VM
4. The TeamCity Azure Plugin creates new VM's based on the snapshot

Here's a powershell script I found that shows how to create a new VM based on a snapshot:

https://github.com/KacperMucha/random-powershell-scripts/blob/master/New-AzureRmVmFromSnapshot.ps1

**Comment by trzombie** [comment]
+1 to that.

**Comment by SaphuA** [comment]
It seems it is now also possible to Capture (new?) VM's right in the Azure Portal. This creates a new resource of type 'Microsoft.Compute/images/' that can be used to create new VM's from. Might be interesting to be able to use these as the basis for new VM's.

**Comment by dtretyakov** [comment]
@SaphuA, thanks for sharing, we'll try to support it and improve UX for cloud image creation.

**Comment by dtretyakov** [comment]
There is a [preview plugin builds](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager) with Managed Images support. To create a new image you need to capture image from VM.

**Comment by BtDevOpsTeam** [comment]
Did the following
- uploaded the [plugin](https://teamcity.jetbrains.com/viewLog.html?buildId=1131803&tab=buildResultsDiv&buildTypeId=TeamcityAzurePlugin_BuildResourceManager)
- restarted TeamCity Server Service
- Actions "Edit" does not work
- "Add Image" is disabled (grey-ed out)

**Comment by dtretyakov** [comment]
@BtDevOpsTeam, thanks for reporting, could you please open the developer console in the browser and share the errors after reloading page?

**Comment by BtDevOpsTeam** [comment]
Thanks for the prompt reply

The most prominent error looks like _ReferenceError: imageType is not defined_

Is this what you are looking for?

**Comment by dtretyakov** [comment]
@BtDevOpsTeam, yes, thanks, will fix it soon.

**Comment by dtretyakov** [comment]
@BtDevOpsTeam, it was fixed in build #87, please check that it works correct.

**Comment by btdevopsteam** [comment]
Thank you for the prompt fix!

Both "Edit" and "Add Image" works

**Comment by dtretyakov** [comment]
Support of Managed Disk Snapshots would not be introduced any soon since Snapshot is a specialized image and we could not use it to set custom data with agent configuration details while creating new vm.
