### ISSUE TITLE
Check for illegal characters in the agent name prefix

### ISSUE THREAD

**Issue by ruipelo** [JetBrains/teamcity-azure-plugin#51]
In azure the Windows computer name cannot be more than 15 characters long, be entirely numeric, or contain the following characters: ` ~ ! @ # $ % ^ & * ( ) = + _ [ ] { } \ | ; : . ' " , < > / ?.

The plugin should check that these criteria are met before accepting the input from the user. Otherwise the user has to go to the azure activity logs to find the reason.

**Comment by dtretyakov** [comment]
Azure naming rules and restrictions: https://docs.microsoft.com/en-us/azure/architecture/best-practices/naming-conventions#naming-rules-and-restrictions

**Comment by dtretyakov** [comment]
Fix will be available in the next plugin build.
