### ISSUE TITLE
Allow PowerShell scripts to be run using provisioning credentials after VM creation

### ISSUE THREAD

**Issue by jacksobt** [JetBrains/teamcity-azure-plugin#59]
It would very helpful if the ability was added to run PowerShell scripts after VM creation using the credentials from the provisioning of the VM for post-configuration tasks.

**Comment by dtretyakov** [comment]
@jacksobt, you could leverage custom template and define custom script extensions as mentioned here:
https://github.com/JetBrains/teamcity-azure-plugin/issues/45#issuecomment-323583428

**Comment by jacksobt** [comment]
Perfect! Thank you, @dtretyakov!
