### ISSUE TITLE
My Azure Cloud configuration is now throwing the following error when loading the page.

### ISSUE THREAD

**Issue by erichexter** [JetBrains/teamcity-azure-plugin#6]
Unable to fetch options: org.apache.http.conn.HttpHostConnectException: Connect to management.core.windows.net:443 [management.core.windows.net/23.102.135.246] failed: Connection timed out: connect

![image](https://cloud.githubusercontent.com/assets/114692/8171287/6152ef72-137c-11e5-81fe-62a2e199d319.png)

**Comment by paksv** [comment]
Please ensure that the TC server can establish connection to management.core.windows.net:443
