### ISSUE TITLE
Allow resource tagging

### ISSUE THREAD

**Issue by btdevopsteam** [JetBrains/teamcity-azure-plugin#60]
@dtretyakov 

Thank you for your enhancement in #36 

Another great enhancement would be to allow resources to be automatically tagged when they are being spawned

**Comment by konste** [comment]
@dtretyakov
What my colleague is trying to say here is that it would be great if cloud profile would allow for the tagging (with arbitrary tags) all resources it dynamically instantiates. Really helpful for costs attribution.
Thank you for your support!

**Comment by dtretyakov** [comment]
@btdevopsteam, @konste, could you try to use [Custom ARM Templates](https://github.com/JetBrains/teamcity-azure-plugin/issues/45) to tag required resources while deployment?

Do you need to specify tag key/value pairs per cloud image?

**Comment by konste** [comment]
@dtretyakov we probably could, but it looks like a major overkill for the purpose. All we really need is a way to specify a few key=value strings (comma separated would do) per Cloud Profile.

**Comment by btdevopsteam** [comment]
@dtretyakov 

Would you be referring to build 102 which installs **SNAPSHOT-20170816163918**?

Here are the options we are seeing when adding a new image, where should we find **Custom ARM Templates**?
![image](https://user-images.githubusercontent.com/30698023/29458631-a9da337e-8452-11e7-8435-e44164cadcad.png)

**Comment by dtretyakov** [comment]
@konste, ok, will consider adding custom tags option.

@btdevopsteam, you should select Image Type as `Template`:
![image](https://user-images.githubusercontent.com/1025927/29459358-87a2b3dc-8423-11e7-8cf9-21dc035639be.png)

**Comment by btdevopsteam** [comment]
Noted with thanks, let us give it a try and update you early next week

**Comment by btdevopsteam** [comment]
It works 👍 

We are able to add custom tags to via template, thanks!

**Comment by btdevopsteam** [comment]
Would be possible to have variable for the VM password? Otherwise we would have to put it in clear withing the template, which is somewhat insecure

Thanks!

**Comment by dtretyakov** [comment]
@btdevopsteam, we could do that as part of issue "Template deployment parameters" #63 once TeamCity core will support [project parameters in cloud profiles](https://youtrack.jetbrains.com/issue/TW-51157).

**Comment by btdevopsteam** [comment]
Sounds good

Thansk!
