### ISSUE TITLE
Plugin should not spawn VMs when all VM are "Scheduled to stop"

### ISSUE THREAD

**Issue by btdevopsteam** [JetBrains/teamcity-azure-plugin#62]
We noticed a behavior where
- if we limit to e.g. 3 VM
- when all 3 VM are "scheduled to stop"
- if demands picks up (of if we click "start")

The plugin would deploy a 4th VM

It would be nice if the plugin would wait for those that are "scheduled to stop" to completely stop and start them instead of deploying extra VMs beyond the limit set (in this example 3)

Thanks!

**Comment by dtretyakov** [comment]
@btdevopsteam, it's a common for all cloud integrations in TeamCity and I suspect that not everyone could agree to wait until all build agents will be stopped which could cause delays for queued builds.
So could you please report it in the [TeamCity issue tracker](https://youtrack.jetbrains.com/newIssue?project=TW&clearDraft=true&c=Type+Feature&c=Assignee+spak&c=Subsystem+Cloud+support) and we'll try to evaluate it?

**Comment by btdevopsteam** [comment]
Please allow me to give a better example
- 5 agents max
- 5 running
- 1 was idling and the plugin tries to stop it so it ends up as "scheduled to stop", this is expected and perfectly fine
- at this time the build queue grows and the plugin then deploys a 6th VM :'(

IMHO, if we wait for that VM to stop then start it, we could avoid getting a newly deployed VM when existing VMs are "scheduled to stop"

The total number of stopped VM could increase well beyond 5 if such scenarios repeat

**Comment by dtretyakov** [comment]
@btdevopsteam, ok, thanks for clarification. You could try to update to the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1) where it was fixed.

**Comment by btdevopsteam** [comment]
Thanks! It works "Scheduled to stop" is considered as active and would not allow additional agents to be spawned
