### ISSUE TITLE
Agents start is slow (takes 10 minutes)

### ISSUE THREAD

**Issue by nachtneblovaK** [JetBrains/teamcity-azure-plugin#66]
We are using TeamCity with your ARM plugin.
When plugin starts agent it takes almost 10 minutes to run agent. Just about 2-3 minutes takes starting VM, rest of the time agent seems to do nothing. But can't build (TC says "There are no fully-running agents").
I tried to dealocated VM in azure portal and start it again. And agent starts build immediately. The problem is just with stoping/starting VM with plugin. 

Do you have any idea why starting agent by plugin takes so long?

**Comment by jacksobt** [comment]
We have also noticed this slowdown.

**Comment by dtretyakov** [comment]
To investigate the cause could you please share the following:
1. From the azure portal: Navigate to the resource group > Deployments -> %agent_name% and share the time spend on the resources deployment
2. Attach the teamcity-agent.log file from the TeamCity: Navigate to the agents -> %agent_name% -> Logs

And attach them into the issue: https://youtrack.jetbrains.com/issue/TW-51449

In my case agent start has taken 8 mins. 

`teamcity-clouds.log`:
```
[2017-09-06 16:37:04,576]   INFO [nio-8080-exec-1] - .instances.StartInstanceAction - Starting cloud instance: profile 'Azure', AzureCloudImage{myName='windows-imag'}
...
[2017-09-06 16:45:05,139]   INFO [nio-8080-exec-7] - .server.impl.CloudEventsLogger - Detected cloud agent "windows-imag1" {id=21}, profile 'Azure', AzureCloudInstance{myName='windows-imag1'} 
```

`teamcity-agent.log`:
```
[2017-09-06 14:42:19,442]   INFO - s.buildServer.agent.AgentMain2 - Agent home is C:\BuildAgent 
[2017-09-06 14:42:19,848]   INFO -   jetbrains.buildServer.SERVER - Starting TeamCity agent 
... upgrade...
[2017-09-06 14:45:52,533]   INFO - buildServer.AGENT.registration - Registering on server via URL http://teamcity: AgentDetails{Name='windows-imag1'}
```

VM creating in azure portal:
![image](https://user-images.githubusercontent.com/1025927/30122425-acca5394-932e-11e7-8732-e72ea2649a6b.png)

So TeamCity build agent got a control after 5,5 mins after deployment start and spent 2,5 mins to upgrade plugins and tools. To speed up it you need to recapture image with TeamCity build agent after each TeamCity upgrade.

You could post an idea regarding increasing vm deployment speed in the [Azure feedback](https://feedback.azure.com/forums/34192--general-feedback) or could open request ticket in Azure portal to investigate the cause of slow deployment [like me](https://twitter.com/dtretyakov/status/893382320840953858).

**Comment by mscrivo** [comment]
We are seeing really slow startup times, even with re-using existing VMs.  The Azure classic plugin does not suffer this problem.  Is there anything we can provide to help diagnose this issue?  It's killing us.

**Comment by mscrivo** [comment]
I've added the requested info/logs to the bug you mentioned.

**Comment by dtretyakov** [comment]
In the [latest ARM plugin version](https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support) it was fixed. Please let me know if solves this problem.

**Comment by mscrivo** [comment]
I've installed it, will let you know how it works

**Comment by mscrivo** [comment]
Seems to work better.  agents are no longer being torn down as often, so it's re-using the existing stuff more.  Thanks!
