### ISSUE TITLE
"Reuse allocated virtual machines" has no effect

### ISSUE THREAD

**Issue by btdevopsteam** [JetBrains/teamcity-azure-plugin#67]
We notice the following behavior for 0.6.0, 0.6.1 and 0.6.2

Suppose we limit to **5** agents
- start 5 agents
- 5 agents appeared in pool
- stop 1 agent
- 1 agent scheduled to stop
- 1 agent stop
- everything is fine till this point

-------

Click start
- expected: the stopped agent is started
- observed: agent **6** is spawned

-------

We reverted to **SNAPSHOT-20170828134512** and the above is no longer observed

Please let us know if we can provide further information to aid the investigation, thanks!

**Comment by dtretyakov** [comment]
@btdevopsteam, could you please also report what kind of image (VHD, Image, Template) do you use for this cloud image?

**Comment by btdevopsteam** [comment]
We are using Image

The abovementioned behavior is noticed after upgrading the plugin (no configuration changes where done)

**Comment by benosman** [comment]
I have also encountered this issue with the versions listed above, and I too am using Image.

**Comment by mscrivo** [comment]
Same issue here

**Comment by dtretyakov** [comment]
Please try to use the latest snapshot build from the [plugin build page](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1&tab=buildTypeStatusDiv) and let me know if it fixes this problem.

**Comment by mscrivo** [comment]
Thank you, I've installed it.  Will let you know how it goes.

**Comment by mscrivo** [comment]
hmm, not sure it's working.  I had agent1-5 created and deallocated after idle builds (i have max instances set to 5), then at some point agent5 was deleted and it created agent6.

**Comment by mscrivo** [comment]
Also seeing this error frequently

> Invalid status code 404 
Hide stacktrace
jetbrains.buildServer.clouds.CloudException: Invalid status code 404jetbrains.buildServer.clouds.CloudException: Invalid status code 404
at jetbrains.buildServer.clouds.azure.arm.connector.AzureApiConnectorImpl$getInstanceDataAsync$1$1.doResume(AzureApiConnectorImpl.kt:205)
at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:53)
at kotlinx.coroutines.experimental.DispatchTask.run(CoroutineDispatcher.kt:120)
at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

Which results in no agents being started.  It usually resolves itself after some time.

**Comment by dtretyakov** [comment]
The latest [snapshot plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1&tab=buildTypeStatusDiv) fixes this problem.

@mscrivo, could you please describe where do you see "Invalid status code 404"? Is it a cloud instance error?

**Comment by mscrivo** [comment]
@dtretyakov It was on the cloud tab of the agents page.  Not on a specific agent instance, but the whole cloud config.

**Comment by dtretyakov** [comment]
@mscrivo, thanks, move it into #69.
