### ISSUE TITLE
Image change is not detected when an VM created from a VHD is updated and recaptured

### ISSUE THREAD

**Issue by ruipelo** [JetBrains/teamcity-azure-plugin#68]
I recently updated my plugin and noticed the new feature from issue #48 and hoped that I would no longer need to manually delete my old VMs whenever I do updates. Unfortunately I noticed that this new feature doesn't work with the way I've been updating my agent VHD. 

What I do when there is a need to change something on the agents is: RDP to an instance created from the VHD, do the changes and recapture the VM to a new VHD. The new feature is based on the blobs Content-MD5, which remains the same when I do this. I currently have 6 VHDs which all have the same Content-MD5. Some other way of identifying changes to the VHD would be needed for this to work.

**Comment by dtretyakov** [comment]
@ruipelo, it should be fixed in the latest [snapshot plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=<default>&tab=buildTypeStatusDiv&guest=1). Instead of MD5 hash now it relies on Etag value of VHD blob file.

**Comment by ruipelo** [comment]
@dtretyakov, I had a change to test the snapshot today and the Etag does really work with my use case. After updating the plugin all machines created with the previous version were deleted after pressing start on the cloud tab of the agents view. I then captured a new VHD and verified that the change was also detected in that case. Much thanks for the continued work on this great plugin!
