### ISSUE TITLE
Is it possible to shutdown agent as soon as build is finished ?

### ISSUE THREAD

**Issue by adnangohar** [JetBrains/teamcity-azure-plugin#72]
I would like to know if it is possible to shutdown an agent as soon as it finishes the build ? Moreover it is not evident what "After the first build" option under "Additional terminate conditions" does. What I have experienced when I enable it is, it just spawns the VM and instantly shuts it down. Would appreciate some more information about this.

**Comment by dtretyakov** [comment]
@adnangohar, there was a problem in plugin. Could you please try to download the [latest ARM plugin version](https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support) and let me know if solves this problem.
