### ISSUE TITLE
No images were found

### ISSUE THREAD

**Issue by thinkbeforecoding** [JetBrains/teamcity-azure-plugin#78]
After upgrading to 2017.2, the Agents/Cloud tab says:
`**You have 1 profile configured.**`
but also:
`No images were found` 

The problem is that there is one ARM template image in the profile, that was working correctly until the upgrade.

I tried to reinstall TC 2017.2 from scratch, recreate the profile with the ARM template, and still nothing.

Is there an incompatibility of the last version of this plugin with 2017.2 ?

With this message I cannot create any cloud agent from TeamCity...

**Comment by dtretyakov** [comment]
@thinkbeforecoding thanks for reporting, please try [upgrading plugin to v0.6.4](https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support) where was fixed compatibility with TeamCity 2017.2 and let me know if it was fixed.

**Comment by thinkbeforecoding** [comment]
The v0.6.4 fixed the 'No images were found problem', but i have another Issue that I'll report in a new ticket.

Thanks a lot.

**Comment by dtretyakov** [comment]
@thinkbeforecoding, thanks.
