### ISSUE TITLE
Arm agent 'Removed' even when reuseVM is checked

### ISSUE THREAD

**Issue by thinkbeforecoding** [JetBrains/teamcity-azure-plugin#80]
The reuseVM checkbox is checked, and the parameter appears correctly as `true` in the xml config:
```
        <param name="reuseVm" value="true" />
```

But the log still report:
```
Removing virtual machine buildagent-4 due to cloud image settings 
```
And the virtual machine deployment is the deleted instead of just stopped.

This logs appears only on the following lines:
```
                if (myImageDetails.behaviour.isDeleteAfterStop) {
                    LOG.info("Removing virtual machine ${instance.name} due to cloud image settings")
                    ...
```
with
```
  START_STOP(false, true),
  FRESH_CLONE(true, false),
  ON_DEMAND_CLONE(false, false);
 ...
  CloneBehaviour(final boolean deleteAfterStop, final boolean useOriginal) {
    myDeleteAfterStop = deleteAfterStop;
    myUseOriginal = useOriginal;
  }
...
  public boolean isDeleteAfterStop() {
    return myDeleteAfterStop;
  }

```
So the isDeleteAfterStop can be true only in the FRESH_CLONE case.
and
```
override fun getBehaviour(): CloneBehaviour =
            if (myReuseVm) CloneBehaviour.ON_DEMAND_CLONE else CloneBehaviour.FRESH_CLONE
```

So the FRESH_CLONE is only returned when myReuseVM is false.

is it equivalent in kotlin to write
```
myImageDetails.behaviour.isDeleteAfterStop
```
and 
```
myImageDetails.getBehaviour().isDeleteAfterStop
```
?

**Comment by dtretyakov** [comment]
@thinkbeforecoding, could you please try to download [the latest snapshot version](https://teamcity.jetbrains.com/repository/download/TeamcityAzurePlugin_BuildResourceManager/lastSuccessful/cloud-azure-arm.zip) of plugin to ensure that this problem was fixed?

**Comment by thinkbeforecoding** [comment]
This is working 😄 
thanks again !

**Comment by dtretyakov** [comment]
@thinkbeforecoding, ok, thanks for confirmation. Could you please download the latest stable plugin build:
https://plugins.jetbrains.com/plugin/9260-azure-resource-manager-cloud-support
