### ISSUE TITLE
Ability to choose storage type

### ISSUE THREAD

**Issue by mscrivo** [JetBrains/teamcity-azure-plugin#83]
## Description

When creating a VM from an image in Azure, you get the option to choose your storage type, either SSD or HDD:

![image](https://user-images.githubusercontent.com/275524/34057459-03c40068-e1a5-11e7-872e-7decb250c8c4.png)

However, in the plugin, there is no such choice and thus all VM's are created on really slow HDD storage.  It would be nice to have the option to select SSD as you do when creating a VM from the image.

## Environment

* TeamCity version:  2017.2
* Azure plugin version: 0.67

**Comment by dtretyakov** [comment]
@mscrivo, you could try to use the [latest snapshot plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1&tab=buildTypeStatusDiv) with ability to select disk type.

**Comment by mscrivo** [comment]
Thanks @dtretyakov .. just tried it and the only option I have is HDD in the dropdown.  Anything else that needs to be setup?  in the portal I can choose SSD and was able to create one manually on SSD.

**Comment by dtretyakov** [comment]
@mscrivo, yes you need to use the following [machine types:](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/premium-storage)

> Premium Storage supports DS-series, DSv2-series, GS-series, Ls-series, and Fs-series VMs.

**Comment by mscrivo** [comment]
yes, we're using DS2v3

**Comment by mscrivo** [comment]
![image](https://user-images.githubusercontent.com/275524/34211516-52f74ce2-e567-11e7-9240-4e31eb3dd85c.png)

**Comment by dtretyakov** [comment]
@mscrivo, thanks, the disk type filter was fixed, you could download the latest plugin version:
https://plugins.jetbrains.com/plugin/9260-azure-support-resource-manager-integration

**Comment by mscrivo** [comment]
working perfectly, thank you!
