### ISSUE TITLE
No images found in CanadaEast region

### ISSUE THREAD

**Issue by mscrivo** [JetBrains/teamcity-azure-plugin#84]
## Description

We're trying to move our build agents from West US to Canada East and when doing that, the plugin tells us that we have no images in Canada East, even though we for sure do. 

## Environment

* TeamCity version: 2017.2.1
* Azure plugin version: 0.67

I believe the issue is casing.  When listing our images using `az image list` the image in Canada East has a location 'CanadaEast' whereas our images in West US show a location of 'westus'.   `az group show -n <resourcegroup>` for the resource group in Canada East shows a location value of 'canadaeast'

**Comment by mscrivo** [comment]
Seems like perhaps `getImagesAsync` is being passed 'canadaeast' and because the images actually have a location of 'CanadaEast', there are no matches.

**Comment by dtretyakov** [comment]
@mscrivo, thanks for reporting. The fix is available in the [latest snapshot plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamcityAzurePlugin_BuildResourceManager&branch_TeamcityAzurePlugin=%3Cdefault%3E&guest=1).

**Comment by mscrivo** [comment]
Thank you @dtretyakov
