### ISSUE TITLE
Azure image-based cloud agent complains about incompatibility of image(machine)

### ISSUE THREAD

**Issue by sshiman** [JetBrains/teamcity-azure-plugin#9]
I have created an image out of Azure machine and trying to use it as a source for TC azure plugin. I do see the incompatibility message on Pools tab for Agents settings when assigning agents to pools (where I do have separate pool created for Azure) and assigned that pool to one project.

If I do create a VM from this image on Azure - then I do not have any problem with running TC build against it, but it complains about incompatibility when Cloud plugin trying to use it from the same image directly!? Why?

-----------
My build configuration is using "Node.js build runner" TC plugin from Eugene Petrenko (https://github.com/jonnyzzz/TeamCity.Node)

This is what I see on the page -> it complains about node.js. Also, it complains about PowerShell (as well as for Command line as well as about environment variables ->

Incompatible runner:
 Node.js NPM

Unmet requirements:
node.js.npm exists  
node.js exists  
powershell_x86 exists  
 

Implicit requirements:
env.SystemDrive defined in Build step: Common: npm config cache

**Comment by paksv** [comment]
When you configure a new cloud image in cloud profile, TC starts one instance of this image and calculates the compatibility (i.e. what builds can be run on agent that will come to server after the instance is started). 

It looks like the cloud image you are using doesn't have Node.js and powershell installed - this is what TC server complains on.

**Comment by sshiman** [comment]
This is not correct. as I said already if I'm using the same image to create standalone VM myself then everything is up and running. The problem is when the same image is in use by plugin. Why?

**Comment by paksv** [comment]
Can you please attach screenshots and teamcity-server.log and teamcity-clouds.log? If you feel this is not secure, you can create an issue at https://youtrack.jetbrains.com (which allows secure attachments) and we can continue there.

**Comment by wblair** [comment]
I encounter the same problem where even a job that is a one line PS command "echo helloWorld" is not compatible with an Azure "image" agent and IS compatible with an Azure "machine" agent that is created from the same image.

I submitted issue https://youtrack.jetbrains.com/issue/TW-42591 with the attachments requested above.

**Comment by dtretyakov** [comment]
Closing since [TW-42591](https://youtrack.jetbrains.com/issue/TW-42591) has been resolved.
